cart/mustShop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("",include("shop.urls")),
    path("user/",include("user.urls")),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

payment/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i))for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from shop.models import  Product
from .cart import Cart
from .forms import CartAddProductForm
# Create your views here.

@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')
def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html',{'cart': cart})

payment/views.py
from django.shortcuts import render

# Create your views here.

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{%  load static %}

{% block title %} Your Cart {% endblock %}

{% block content  %}
<h1>Your Cart</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Image</th>
         <th>Product</th>
         <th>Quantity</th>
         <th>Remove</th>
         <th>Unit Price</th>

    </tr>
    </thead>
<tbody>
{% for item in cart %}
{% with product=item.product %}
<tr>
    <td>
        <a href="{{ product.get_absolute_url }}">
<img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/no_image.png' %}{% endif %}" >
</a>
    </td>
<td>{{ product.name }}</td>
<td>{{ item.quantity }}</td>
{#<td>#}
{#    {{ item.update_quantity_form.quantity }}#}
{#    {{ item.update_quantity_form.override }}#}
<td>
    <form action="{% url "cart:cart_remove" product.id%}" method="post">
        {% csrf_token %}
         <input type="submit" value="Remove">
    </form>

</td>




<td>
    <form action="{% url "cart:cart_remove" product.id %}" method="post">
        <input type="submit">
    {% csrf_token %}
    </form>
</td>
<td class="num">₦{{ item.price }}</td>
<td class="num">₦{{ item.total_price }}</td>
</tr>
{% endwith %}
{% endfor %}

<tr class="total">
    <td>Total</td>
    <td colspan="4"></td>
    <td class="num">₦{{ cart.get_total_price }}</td>
</tr>
</tbody>
</table>
    <p class="text-right">
        <a href="{%url  "shop:product_list" %} " class='button light'>Continue Shopping</a>
        <a href="{% url "order:order_create" %}" class="button">Checkout</a>

    </p>
{% endblock %}